### ISSUE TITLE
Settings Not Getting Updated in 4.1.2

### ISSUE THREAD

**Issue by Updula** [checkout/checkout-woocommerce-plugin#112]
The latest version seem to have a bug not allowing settings to be updated. Issue resolved when back to 4.1.0

**Comment by avish-bisbeehurry-cko** [comment]
@Updula can you provide more details on the bug. All settings are updated correctly from my end. Any specific case you can share with us?

**Comment by robintriggmn** [comment]
I have replicated this issue on plugin 4.1.2, WordPress 5.3, WooCommerce 3.8.1.

**Comment by Updula** [comment]
Hope it gets fixed.

**Comment by avish-bisbeehurry-cko** [comment]
Issue fixed in version 4.1.3. Make sure to update the module.
