### ISSUE TITLE
Settings Wiped Out Upon Saving

### ISSUE THREAD

**Issue by Updula** [checkout/checkout-woocommerce-plugin#115]
When saving main settings it saves fine, but when moving to another tab (Card Settings) and save those, main settings get wiped out!

**Comment by avish-bisbeehurry-cko** [comment]
@Updula thank you for reporting this issue. A new release v4.1.4 is available with the bug fix. Can you update the module. This should permanently fix the issue.

**Comment by Updula** [comment]
@avish-bisbeehurry-cko Thanks for the quickfix, it is now working properly, but we still face some issues with saved cards settings:

- When option "Require CVV For Saved Cards" is disabled, the CVV error is solved but when using the saved card, a 20030 Format Error occur on the used saved card.
- When option "Require CVV For Saved Cards" is enabled, an error is always shown upon submit to enter card CVV but no input is shown for the user to input that number.

**Comment by avish-bisbeehurry-cko** [comment]
@Updula Can you confirm if you are using sandbox or live environment? Please make sure to use the cards available [here](https://docs.checkout.com/docs/testing#section-credit-cards)

Unfortunately, I could not replicate the 1st issue. The saved cards are working fine on my end and the payment is processing correctly.

The 2nd issue is related to a display issue. If you click on new card and back to the saved card the field to enter cvv will be displayed. A fix will be provided soon for this issue.

**Comment by Updula** [comment]
@avish-bisbeehurry-cko I was testing this on Live. Perhaps the first error (Format Error) is caused due to missing CVV which is related to the second issue.

**Comment by Updula** [comment]
A new issue with ApplePay appeared in latest 4.1.4: JS Syntax Error: Unexpected EOF in line `var data = JSON.parse(outcome);`

I reverted back to 4.1.0 and all is good now.

**Comment by avish-bisbeehurry-cko** [comment]
@Updula Can you update to version 4.1.5. This should fix both issue with card cvv and apple pay.

**Comment by Updula** [comment]
@avish-bisbeehurry-cko Updated and now I saved cards error is fixed after CVV is visable.

- [ ] Radio buttons for choosing "use a new card" or saved card should always default selection on first available option.
- [ ] The text "Card Code" is under "woocommerce-square" domain name, which we cannot translate.
- [ ] Apple Pay is still broke in latest version, here's screenshot of JS error in console:

![img](https://i.imgur.com/4p8pYMS.jpg)

- [ ] Also another issue is compatibility with custom checkout fields, in our cause our issue was fixed by adding this to apple pay class file:

`if(name === 'mobile/email') {
                            return  true;
                          }`

**Comment by Updula** [comment]
@avish-bisbeehurry-cko appreciate your help with the above.

**Comment by avish-bisbeehurry-cko** [comment]
@Updula we will check those issues and get back to you accordingly.

**Comment by avish-bisbeehurry-cko** [comment]
@Updula a new version is available. Can you please update to v4.1.6, this should fix all the issues except for the custom code you added

**Comment by Updula** [comment]
@avish-bisbeehurry-cko thank you! I tested and all good with creditcard payments.

Although Apple Pay is now showing a 422 error, token_invalid: The endpoint did not accept the request. (Code: 422)

4.1.0 ApplePay works well

**Comment by Updula** [comment]
@avish-bisbeehurry-cko All works well now, thanks!

only wish for future releases to have internal text domain
