### ISSUE TITLE
Few Issues

### ISSUE THREAD

**Issue by Updula** [checkout/checkout-woocommerce-plugin#126]
Hi there, we have noticed few issues in the plugin.

**1. Duplicate stock reduction:**

This is due to manually handling stock using `wc_reduce_stock_levels` function. 

A single function can take care of stock, status, and empty cart instead: `$order->payment_complete();` - as per WC docs: https://docs.woocommerce.com/document/payment-gateway-api/

**2. Callback and webhook overlapping:**

We noticed that some orders get completed or fulfilled twice! Upon further tracking it turns out that the webhook sometimes runs for callback-fulfilled orders (3d secure enabled). It's very hard to replicate this issue but we applied a quick fix that seem to fixed it so far: adding `sleep(15);` at the beggining of `WC_Checkout_Com_Webhook` class

Hope these get fixed so we can upgrade safely.

**Comment by avish-bisbeehurry-cko** [comment]
@Updula Unfortunately I cannot replicate issue 1) as the stock was reduced as expected. Can you confirm which version of the plugin you are currently on? Also can you provide a specific scenario where we can test the duplicate stock reduction.

2. This can be fixed earily by setting "Capture Delay" to 0.02 when configuring the module. Let me know if this works.

**Comment by Updula** [comment]
@avish-bisbeehurry-cko Hi, the duplicated stock reduction happens in coordination with the second issue. When an order is being marked twice as "completed" this results in double stock reduction. Not to mention that current code is simply outside of WC guidelines `$order->payment_complete();`

We're running latest WC + WP with checkout plugin at `4.1.8` with our manually applied fixed, issue did not happen for 2 months now since I placed this ticket.

**Comment by avish-bisbeehurry-cko** [comment]
#145
