### ISSUE TITLE
The WC_Cart::get_item_data function is deprecated

### ISSUE THREAD

**Issue by thrmda** [checkout/checkout-woocommerce-plugin#134]
I'm facing this error when trying to checkout :
The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data., referer: http://mtajer.net/product/test/

Im using the last version of checkout-WC And last of WP And last of WC

**Comment by avish-bisbeehurry-cko** [comment]
@thrmda Can you please confirm which version of the plugin you are currently using? I would suggest you update to our latest release.
