### ISSUE TITLE
formbuttonLabel and buttonLabel should be added for checkoutjs

### ISSUE THREAD

**Issue by avish-bisbeehurry-cko** [checkout/checkout-woocommerce-plugin#20]
formbuttonLabel and buttonLabel should be added in window.checkoutIntegrationCurrentConfig.
The button to add card is currently displaying Pay Now instead of "Add Card"

![image](https://cloud.githubusercontent.com/assets/9551963/17057344/72b5783e-502a-11e6-8db2-9e73e6f5e27d.png)

**Comment by nicolas-maalouf-cko** [comment]
This has been removed in the latest version of the plugin
