### ISSUE TITLE
New version showing php error

### ISSUE THREAD

**Issue by noman2590** [checkout/checkout-woocommerce-plugin#264]
I am using checkout.com WordPress plugin for a store. Yesterday when I updated the plugin to v4.3.9, it started showing PHP error. I had to rollback to previous version. Can you check what's the issue with latest version.

**Comment by SanketChodavadiya** [comment]
Hey @noman2590 
Thank you for reporting an issues.

We have just released new version 4.4.0 with new improvements. It should fix this issue.

We are closing this issue for now as its resolved. If we missed something please leave comment and we will take a look.
