### ISSUE TITLE
Urgent! Hiding "Refund" button for other payment methods!

### ISSUE THREAD

**Issue by valmedia** [checkout/checkout-woocommerce-plugin#265]
https://github.com/checkout/checkout-woocommerce-plugin/blob/b979290f3492aa11483dab087dfaf3d152797873/woocommerce-gateway-checkout-com/woocommerce-gateway-checkout-com.php#L269

This code is hiding the refund button for other payment methods! Please fix it asap.

Thanks,
Tony

**Comment by SanketChodavadiya** [comment]
Hey @valmedia
Thank you for reporting an issues.

We have just released new version `4.4.0` with new improvements. One of them is we have now enabled refund functionality for APMs.

We are closing this issue for now as its resolved. If we missed something please leave comment and we will take a look.

**Comment by valmedia** [comment]
This is not the same. The problem is your code is hiding the refund button for other plugins' payment methods.

> Hey @valmedia Thank you for reporting an issues.
> 
> We have just released new version `4.4.0` with new improvements. One of them is we have now enabled refund functionality for APMs.
> 
> We are closing this issue for now as its resolved. If we missed something please leave comment and we will take a look.
