### ISSUE TITLE
Duplicate orders with latest plugin update

### ISSUE THREAD

**Issue by valmedia** [checkout/checkout-woocommerce-plugin#283]
We are having lots of duplicate orders ever since upgrading to latest version. Ever since rollback to older version, we have not seem new duplicate orders (2 hours right now since rollback).

**Comment by SanketChodavadiya** [comment]
Which version you have rollback to?

**Comment by valmedia** [comment]
> Which version you have rollback to?

v4.3.9 - 16 hours since rollback and no duplication.

From looking at the way duplicate orders are created, the customers think they haven't paid so they are not being redirected to the order confirmation page.

Only 10% of the orders are like this but definitely, it is happening before.

**Comment by valmedia** [comment]
Sorry, it seems like it is happening with v4.3.9 as well. I will monitor and see. Enabled debug log.
