### ISSUE TITLE
Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\choose_handler()

### ISSUE THREAD

**Issue by vijayhardaha** [checkout/checkout-woocommerce-plugin#312]
`GuzzleHttp` is conflicting with many other plugins. I am unable to update to the latest version.

To check the conflicts, install & activate one of these plugins `googleanalytics`, `mailjet-for-wordpress`

There could be many other plugins that can conflict on `GuzzleHttp`, it will be good if you can prefix the namespace and then use it.

**Comment by vijayhardaha** [comment]
**- Update -**

Removing platform config from the composer.json and then installing the no-dev deps, solves the issue. 
```
"platform": {
     "php": "7.2"
}
```

**Comment by SanketChodavadiya** [comment]
We have fixed above issue.
