### ISSUE TITLE
Sandbox Not Completing Payment Transaction

### ISSUE THREAD

**Issue by fitucas** [checkout/checkout-woocommerce-plugin#65]
**woocommerce-checkout-non-pci-gateway**

Sandbox is not completing the payment transaction. The transaction status is showing as what is configured/defined in wp-admin ex. "On Hold" or "Processing". While Live is completing the transaction directly.

Since the "Payment Action" is set to "Authorize and Capture" for Sandbox, it should complete or reject the transaction.

![wctransaction](https://user-images.githubusercontent.com/36146986/35789915-e470d13c-0a58-11e8-8b25-ee38dff1ed9a.JPG)
![wccheckoutconfig](https://user-images.githubusercontent.com/36146986/35789916-e4a9a58e-0a58-11e8-9785-8620f17daee4.JPG)

**Comment by nicolas-maalouf-cko** [comment]
Hi,

Are you swapping keys accordingly when switching environments?

Can you please make sure the webhook URL is configured as described in the readme file in your account on the sandbox hub?

*example.com/wp-content/plugins/woocommerce-checkout-non-pci-gateway/controllers/api/webhook.php*

Here is how you can configure this URL on your account (Manage Channel URLs section):
https://docs.checkout.com/the-hub/system-administration/business-level-settings

**Comment by fitucas** [comment]
Thank you Nicolas for pointing that out.

**Comment by dig814** [comment]
I seem to be having the same issue. I have a dev site and a live site. On the dev site, using sandbox credentials, it will only authorize and then just sits in that state. Live site works as intended. I tried checking ever webhook setting on checkout.com
In my checkout.com sandbox, the order is captured but the status never changes in Woo.

I was finally able to get the whole workflow completed if I enable 3DS in the plugin settings. Is this a bug in the plugin? The link above no longer works. Any ideas?
