### ISSUE TITLE
Apple Pay Gone?

### ISSUE THREAD

**Issue by Updula** [checkout/checkout-woocommerce-plugin#88]
Seems like it's commented out. Are you planning to re-add it?

**Comment by avish-bisbeehurry-cko** [comment]
@Updula Apple pay is still under development. Once this is done we will create a release.

**Comment by Updula** [comment]
@avish-bisbeehurry-cko Good to know, we will continue using prev version until this is ready.

BTW is it possible to show the Apple Pay button in a webview app, within WooCommerce checkout page? It works only on Safari but never in app.

I assume it's because using WKWebView and not SFSafariViewController - any way to bypass this? Or does the button need to be built inside the app in this case, and create the order via WC REST.
