### ISSUE TITLE
PHP Notice: Undefined variable: is_mada_token

### ISSUE THREAD

**Issue by netzkollektiv** [checkout/checkout-woocommerce-plugin#97]
If error reporting is set to show notices (display_errors = 1) the plugin does break the checkout:

PHP Notice:  Undefined variable: is_mada_token in /var/www/html/wp-content/plugins/woocommerce-gateway-checkout-com/includes/class-wc-gateway-checkout-com-cards.php on line 232

This leads to 

`if(is_mada == 1){
                                    if(this.value === '
Notice: Undefined variable: is_mada_token in /var/www/html/wp-content/plugins/woocommerce-gateway-checkout-com/includes/class-wc-gateway-checkout-com-cards.php on line 232
'){`

**Comment by avish-bisbeehurry-cko** [comment]
Hi @netzkollektiv,

Thank you for reporting this issue. Note that this is fixed already and available on our dev branch. We will soon release a new version of the plugin with some bug fix and improvements.

**Comment by avish-bisbeehurry-cko** [comment]
Closing the issue as its been fixed already
